name: CI-CD Setup
on: workflow_dispatch
jobs: 
  slack-notification:
    runs-on: build
    steps:
      - name: Send notification to slack
        uses: slackapi/slack-github-action@v2.1.0
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK }}
          webhook-type: incoming-webhook
          payload: |
            text: "Build Started"
            channel: "dev-testing"
  Build:
    runs-on: ubtuntu:latest
    needs: slack-notification
    steps: 
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Docker Login
        uses: docker/login-action@v3.4.0
        with: 
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build docker image
        run: docker build -t ${{ vars.DOCKER_USERNAME }}//mk-edify:latest
      - name: Push Docker image
        run: docker push ${{ vars.DOCKER_USERNAME }}//mk-edify:latest
  deploy:
    runs-on: build
    needs: build
    steps: 
      - name: deploy and run container
        run: |
          docker pull ${{ vars.DOCKER_USERNAME }}//mk-edify:latest
          docker run -d -p 80:80 --name ${{ vars.DOCKER_USERNAME }}//mk-edify:latest
      - name: Notify Slack - Deployment Completed
        uses: slackapi/slack-github-action@v1.25.0
        with:
          payload: '{"text":"✅ Deployment Completed for mk-edify"}'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
